# Site settings
title:       Paul Roland Lambert	
email:       pr@prlambert.com
author:      Paul Roland Lambert
description: "Paul's personal website."
baseurl:     ""
url:         "http://www.prlambert.com"
production_url : www.prlambert.com

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username:
stackoverflow_id:
twitter_username: prlambert
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
