# Site settings
title:       PRL 
email:       prl@prlambert.com
author:      Paul Roland Lambert
# description: "Paul's website."
baseurl:     ""
url:         "http://www.prlambert.com"
production_url : www.prlambert.com

plugins: [jekyll-paginate]

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: prlambert

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username: prlambert
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# # Build settings
permalink:    pretty
paginate:     10
sass:
  compressed: true
